### ISSUE TITLE
Delay between simultaneous notes

### ISSUE THREAD

**Issue by weavermedia** [djipco/webmidi#102]
When I send out a chord there's audible slurring of the notes. When I send the same chord direct to the synth there is no slur. Is this expected behavior?

```
note = 60
notes = [note - 12, note - 2 , note + 2, note + 3, note + 7]
output.playNote(notes)
```

Audio clip with first 2 chords via WebMIDI and second two chords direct: https://wmd.d.pr/gKE9X7

**Comment by djipco** [comment]
Hmm... that's an interesting problem which I have not noticed before. The question is: where does the lag come from? Is it from Webmidi.js, from the Web MIDI API, from the MIDI layer of your OS, etc.

Can you provide a little more information on your environment (most notably browser and OS) ?

**Comment by weavermedia** [comment]
Chrome 78.0.3904.108 on macOS 10.13.6

I should mention I have about 20-30 Chrome tabs open between various windows and the tests I'm doing with Webmidi.js are in a CodePen page, which might add some overhead?

**Comment by djipco** [comment]
I'm not sure what CodePen does behind the scene and the number of tabs shouldn't really be a problem but, just to be sure, can you do the test with a local HTML page in a single tab?

**Comment by djipco** [comment]
Are you using an external hardware synth or sound module by any chance? When I configure WebMidi.js to use my Mac's IAC driver and then use this driver inside my DAW (Reaper), there's no slurring at all. 

If you are using an external device, maybe the problem is further down the chain (USB interface, MIDI cable, etc.)

**Comment by damonholzborn** [comment]
Are you using the "all" channel? If so, try setting the channel instead. I've found the "all" channel results in MIDI bottleneck.

**Comment by djipco** [comment]
@damonholzborn Thanks for your comment. I'm starting to question whether "all" is a good idea...

**Comment by damonholzborn** [comment]
I think for sending messages probably not. I find it clogs up in all but the least demanding situation. Since the listeners are only dealing with data when it's received, of course,  this shouldn't be a problem for the various listenings (and as far as I can tell, it in fact doesn't), just for senders.

You'll have to check this to confirm, but if I remember right, MIDI traditionally has the concept of "all" for receiving messages (omni mode), but sending is always on a specific channel. So keeping to that tradition would be conceptually correct so shouldn't offend too many people.

**Comment by djipco** [comment]
Since I haven't heard back from @weavermedia, I'm going to close this and chalk the problem up to sending on all channels (which is probably not a good idea anyway).
