### ISSUE TITLE
rp-18 link is broken

### ISSUE THREAD

**Issue by takyano** [djipco/webmidi#139]
**Describe the bug and how to reproduce it**
In the 2.5.2 documentation under Output Class > Methods > decrementRegisteredParameter and incrementRegisteredParameter, the link to rp-18, http://dev.midi.org/techspecs/rp18.php gives me a "This site can’t be reached" in Chrome

**Environment:**
Specify the environment where you are witnessing the problem:
Windows 10
Chrome
https://webmidijs.org/docs/v2.5.2/classes/Output.html

**Additional context**
Firefox is same

it's been converted to a pdf linked from this page:

https://www.midi.org/specifications-old/item/the-midi-1-0-specification

free registration required.

**Comment by djipco** [comment]
Thanks for the heads-up @takyano. The MIDI Consortium has the unfortunate habit of changing links to key pages such as the specification. Someone on their team should probably read [Cool URIs don't change](https://www.w3.org/Provider/Style/URI) by Tim Berners-Lee (1998).

Anyway, since it is now impossible to link directly to the relevant information and, worse, they enforce registration, I decided to remove the link. I also took this occasion to update other links that had bee moved around.

Cheers!
