### ISSUE TITLE
TypeError: Cannot set property navigator of #<Window> which has only a getter

### ISSUE THREAD

**Issue by jjeff** [djipco/webmidi#221]
Migrating my Electron-based app from WebMidi 2 to WebMidi 3, I get this error in the renderer console when attempting to boot my app:

```
TypeError: Cannot set property navigator of #<Window> which has only a getter
    at Object../node_modules/webmidi/dist/cjs/webmidi.cjs.min.js
```

I'm guessing this is related to this code at the top of WebMidi.js:

```JS
if (Utilities.isNode) {
  let jzz;
  eval('jzz = require("jzz")');
  global["navigator"] = jzz;
}
```

Maybe I'm misunderstanding, but it looks like this code says: "If we're running Node, then we must not be in a browser window, so we can create our own navigator object." However, in the case of Electron, that's a false assumption. Electron can... and often does run Node in the browser window - or the "renderer" process as Electron calls it. So attempting to redefine the navigator property of the global object (aka `window` in the renderer) produces an error and the renderer fails.

Again, I'm just guessing, but maybe this code should say something more like:

```JS
if (Utilities.isNode && !window.navigator) {
  let jzz;
  eval('jzz = require("jzz")');
  global["navigator"] = jzz;
}
```

**Comment by djipco** [comment]
With version 3, Node.js support was added to the library. When the library is run within the Node environment, the `jzz` module is imported because it provides the missing Web MIDI API.

However, as you are pointing out, detecting the actual appropriate environment is tricky. Your suggestion makes perfect sense, but it would force you to use the browser implementation instead of the Node one. Is that appropriate? Should I add an option to `enable()` to force one or the other.? I'm just not sure how Electron works (or NW.js, or React Native, etc.). 

In Electron, are both `Utilities.isNode` and `Utilities.isBrowser` returning true?

**Comment by djipco** [comment]
Can you try v3.0.10 and tell me if it helps?

**Comment by jjeff** [comment]
It helps! No more error. Looks like things are working now.
