### ISSUE TITLE
Proposal: .gitignore dist/

### ISSUE THREAD

**Issue by jjeff** [djipco/webmidi#253]
Having the `dist/` directory in Git makes pull requests unnecessarily confusing and unwieldy.

I'm guessing that 98% of users are using WebMidi from the npm package. I propose: 

1. Remove the `dist/` directory from the Git repository - as the first commit
2. Then add `dist/` to the `.gitignore` file - as the second commit

Then you'd have a workflow where the `dist/` directory gets built locally before testing and/or publishing to npm. But there wouldn't be a lot of diff craziness in pull requests or commits.

**Comment by djipco** [comment]
Yes, I agree.

The only drawback is for those who just want to grab the IIFE version and run with it. I guess that, in such a case, they could simply retrieve [webmidi.iife.js](https://cdn.jsdelivr.net/npm/webmidi@3.0.15/dist/iife/webmidi.iife.js) from JSDelivr.

I guess we should adapt the [Installing manually](https://webmidijs.org/docs/getting-started/installation#installing-manually) section of the documentation to reflect that.

**Comment by jjeff** [comment]
I don't have much experience with this, but I think you could do process with GitHub Releases similar to npm publish. So there would be a .zip containing the npm-like content that people could download from GitHub. I'll bet there's a CLI tool for this somewhere.

**Comment by Vexcited** [comment]
Hello, I want to help for this issue !

I've already forked the project and made some modifications.

- I added `dist` to `.gitignore`
- I removed every commit lines in script and removed the build and commit scripts in `package.json`.

I am currently doing the modifications in docs to use JSDelivr for IIFE.

Now for the releases, I think we could rewrite current script in `scripts/release/release.js` to, instead of commit the dist folder, release it to GitHub Releases.

**Comment by djipco** [comment]
Your help is very much appreciated!

If we are going to rework this, we probably should look at [Release It!](https://www.npmjs.com/package/release-it). It simplifies several of the necessary steps involved when releasing a new version. It would, amongst other things, allow us to create a GitHub tagged release which means the instructions in the [Installing Manually](https://webmidijs.org/docs/getting-started/installation#installing-manually) section of the documentation would stay the same.

Even if it's an interactive tool, it can still [be used programmatically](https://github.com/release-it/release-it/blob/HEAD/docs/recipes/programmatic.md).

**Comment by Vexcited** [comment]
> Even if it's an interactive tool, it can still [be used programmatically](https://github.com/release-it/release-it/blob/HEAD/docs/recipes/programmatic.md).

From what I've seen, I don't think we should do something programmatic anymore if we're using this tool because we can define a `release-it` configuration directly in our `package.json` and then call their `release` command in the NPM scripts.

Also, we need a GitHub token to programmatically release to GitHub Releases, so I think we should use the interactive way in the NPM scripts to override this (and use the browser release way as it says in the [GitHub Releases part of the library](https://github.com/release-it/release-it/blob/master/docs/github-releases.md#github-releases))

Let me know what do you think about it !

**Comment by djipco** [comment]
> From what I've seen, I don't think we should do something programmatic anymore if we're using this tool because we can define a release-it configuration directly in our package.json and then call their release-it command in the NPM scripts.

If everything can be configured in `package.json`, that's the way to go.

> Also, we need a GitHub token to programmatically release to GitHub Releases, so I think we should use the interactive way in the NPM scripts to override this

Setting a token isn't hard to do but I guess we should experiment to see what works best.

**Comment by Vexcited** [comment]
Okay, I'll try to implement that.

About the token, it's just about setting `GITHUB_TOKEN` in environment when the script is running.

**Comment by djipco** [comment]
> Guess that would be the easiest and fastest way to implement the feature.

Yes, exactly!

**Comment by djipco** [comment]
Thanks to @Vexcited and his work on PR https://github.com/djipco/webmidi/pull/254, this has been implemented. I had to create a few releases to nail down all the details but it seems stable now.

P.S. Users who want to download the library manually can go to the [latest release page](https://github.com/djipco/webmidi/releases/latest).
