### ISSUE TITLE
Listener class is not being exported

### ISSUE THREAD

**Issue by Zorby-dev** [djipco/webmidi#301]
**Description**
The Listener class (and maybe some others) are not being exposed to the user, so it's impossible to use them in type definitions. Example:
```ts
import WebMidi from "webmidi"

class MidiManager {
    private activeListeners: WebMidi.Listener[] // Not possible -- Listener class is not exported

    ...
}
```

**Environment:**
  - Library version and flavour: CJS 3.0.21
  - Runtime: Browser (Webpack)
  - Language: Typescript
  - Operating system: Ubuntu Linux 20.04

**Details**
None

**Comment by Zorby-dev** [comment]
I found that adding `export` before the class declaration in `webmidi.cjs.d.ts` like so:
```ts
export declare class Listener {
    ...
}
```
works as a very hackish work-around, but I'm not familiar with your build system (or any build systems in general as I've never made a ts library before) so I have no idea how to *actually* fix it.

**Comment by djipco** [comment]
The [`Listener`](https://github.com/djipco/webmidi/blob/master/typescript/webmidi.d.ts#L543) and [`EventEmitter`](https://github.com/djipco/webmidi/blob/master/typescript/webmidi.d.ts#L253) classes are already declared in [`webmidi.d.ts`](https://github.com/djipco/webmidi/blob/master/typescript/webmidi.d.ts) but they are not exported. It was done this way because these two classes are actually part of a separate package called [`djipevents`](https://djipco.github.io/djipevents/index.html). If there is no harm in exporting them from [`webmidi.d.ts`](https://github.com/djipco/webmidi/blob/master/typescript/webmidi.d.ts) I could easily do it. However, not being too familiar with TypeScript, I'm not sure of the implications. Could it cause issues?

**Comment by Zorby-dev** [comment]
As far as I know it should not cause any harm, as the declarations in `webmidi.d.ts` are just typings -- they only tell the typescript compiler how the data structures "look" and will not collide with / override the javascript definitions.

**Comment by djipco** [comment]
This has been pushed in release v3.0.22. Thanks for suggesting this enhancement.
