### ISSUE TITLE
Show sent/received mesages in hex/dec

### ISSUE THREAD

**Issue by cunka** [djipco/webmidi#35]
Would be nice to show the full hex string omitted by the output port as well as what is received on the input port for SYSEX. This would help in diagnosing transmitted and received messages.

**Comment by cotejp** [comment]
I guess I could fire events as raw data is going out and coming in. However, this feels a bit heavy just for the sake of debugging. It will add overhead and I'm not sure how useful it would really be. 

You can always view MIDI traffic by using third party tool such as [MIDIMonitor](https://www.snoize.com/MIDIMonitor/) (I'm sure there's an equivalent on Linux and Windows).

Another option would be for WebMidi.js to have a `DEBUG` mode which would have to be manually activated for those extra events to be triggered.

What do you think, @cunka?

**Comment by cotejp** [comment]
I understand. Let me think about how to properly do this. Thanks a lot for your input.

**Comment by djipco** [comment]
Okay, I did a bit of thinking about this. Here are my observations:

  1. When you listen for `sysex` events, the `data` property of the event object does show you the raw data as a `Uint8Array`. So you already have a window into what's coming in.
  2. Regarding what's going out, adding listeners for outbound messages on the `Output` object does not feel right. I mean, since you are the one crafting the messages, you can simply inspect them before you send them, right? Also, this would mean adding `addListener()`, `hasListener()`, `removeListener()` and a bunch of other cruft just to trigger (and manage) this single event event.

For completeness, I did add a `midimessage` event on the `Input` object. This allows one to listen to all incoming messages. This change will appear with release 2.1 but you can test it out by using `/src/webmidi.js`.

I hope this makes sense. If it does not, feel free to reopen and comment.
