### ISSUE TITLE
Parse received NRPN messages

### ISSUE THREAD

**Issue by hems** [djipco/webmidi#43]
I'm planning to port this max/msp javascript so it will work on "webmidi" library.

While I don't get to this part of my project, I would like to share the current parser I have on a Max/MSP prototype ( the core functionality was borrowed from an article written by Chris Hector from Dave Smith Instruments ) available here so if anyone else is interested in working this out there would be a great starting point ( basically the algorithm is entirely written, just need to be ported really ).

https://gist.github.com/hems/8246279cf28e8607fb0167da8b3deb9a

Unfortunately, I only have 1 synth that sends and receives NRPN so it's the only synth I managed to test this and it works like a charm ( i'm able to send and receive 4096 ticks per knob ). 

I'm not sure if there are details to it, the only thing I know other synths will use NRPN but have less resolution, so if anyone knows about any other NRPN particularity please go ahead and post it here.

**Comment by djipco** [comment]
> Unfortunately, I only have 1 synth that sends and receives NRPN ...

That's one more than me! If you have questions trying to implement this, just give me a shout. Cheers!

**Comment by djipco** [comment]
Hello Dylan,

I'm not sure what you are asking. WebMidi.js does a method to set non-registered parameters ([setNonRegisteredParameters](http://djipco.github.io/webmidi/latest/classes/Output.html#method_setNonRegisteredParameter)). However, since NRPN are not standardized, there's not much else I can do on my side. 

WebMidi.js also has methods to increment and decrement **registered** parameters but those are different from NRPNs.

**Comment by DJenken** [comment]
I was wondering specifically about how I parse NRPN Input from an external hardware midi controller. I have knobs set up on the controller to send Increment / Decrement messages when they are twiddled, and I have each knob set to have distinct MSB and LSB values respectively. In logging the control change messages I receive I was having trouble figuring out where the MSB and LSB values were being passed to the callback data, I have gotten past that issue however and am now able to see the MSB and LSB values being sent as the third element of the data array of the parameter of the control change listener. Now I am working on figuring out how to parse the separate increment / decrement messages of the input listeners. At this point I am unable to differentiate between the knobs through the Increment / Decrement messages alone, and it seems I'll have to keep track of the other incoming messages in order to use separate knobs set up in this way to control distinct parameters in my app.

Sorry for being verbose, I realize I'm still very much talking through the problem with myself, and only just learned about NRPNs in general in the past few days. I do believe I am on track to solving the issue I am facing and will reach out if I have any more specifically targeted issues.

**Comment by djipco** [comment]
>I do believe I am on track to solving the issue I am facing and will reach out if I have any more specifically targeted issues.

Do not hesitate to do so. Cheers!
