### ISSUE TITLE
[NEW VERSION] Thinking about using typescript even in real sources

### ISSUE THREAD

**Issue by TimSusa** [djipco/webmidi#68]
As far as I see a types file was created for webmidi sources, but the sources at its core aren´t using typescript at all. Maybe it would be good to use typescript globally and establish using type-script-compiler for the more modern version (personally I do not like typescript, but this seems to be an important question for a lot of people)? 

Furthermore, I just want to have mentioned this guy: https://github.com/denoland/deno , which seems to be very promising for me to invest in the future...

**Comment by djipco** [comment]
I have not used TypeScript at all. @mmmveggies contributed the `.d.ts` file because it was needed for him to use the lib in a TypeScript project. Unless there is a strong reason to move to TypeScript (and in the spirit of keeping things simple), I'd rather stick to vanilla JavaScript. 

P.S. I appreciate your input. As you can see from the code, it's been a while since I looked at this project but I have lots of ideas for v3 and your input is very valuable.
