### ISSUE TITLE
[NEW VERSION] Upgrade to latest LTS node / npm version and make use of actual ECMA Script Features

### ISSUE THREAD

**Issue by TimSusa** [djipco/webmidi#69]
As far as I can say the latest node LTS version can safely be used (atm 10.15.3 https://nodejs.org/en/download/). It is now possible to use advanced ECMA Features without using the whole boilerplate of babel compiler. In that manner the sources of webmidi could be updated in a simple modern way using const, let, spread and maybe function parameter initializers (which lead to help your ide to guess the right type) etc pp.

This would require a change to package.json

```
  "engines": {
    "node": "*"
  },
```

**Comment by djipco** [comment]
WebMidi.js does not have official Node.js support. I did some early tests which mostly worked but it would need more testing. Details in issue #15.

In any case, v3 will definitely be using ES6+ syntax enhancements. In fact, I intended to do a clean rewrite...

**Comment by fpassa** [comment]
[Deprecation] Web MIDI will ask a permission to use even if the sysex is not specified in the MIDIOptions since around M82, around May 2020. See https://www.chromestatus.com/feature/5138066234671104 for more details.

How do you deal with this error? I was under electron App, trying to send a MIDI output note. I can access WebMidi devices, see inputs and output ports, but at the time of attempting to send a note, I can see in the console the above message. Electron uses Chromium as far as I know as browser.

Any idea?

**Comment by djipco** [comment]
This is not an error. It's a deprecation warning. As far as I can guess without seing actual code, this is probably not related to your problem. I believe Electron uses the `chrome-extension:` protocol which is considered to be a secure origin. I know NW.js (a software similar to Electron) does. If that's the case, your code should just work in Electron.

You can read about [secure origins](https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features) on the Chromium website.

P.S. I'm not sure why you added this comment here. If you feel you found a bug, you should open a new ticket. If you need help, you can always ask your question on the [forum](https://webmidijs.org/forum/). Cheers!

**Comment by fpassa** [comment]
N'inquiète pas Jean-Philippe!

I was able to fix the issue, don't worry. Indeed, for any other facing the same issue, the fix is to ensure Sysex = true on WebMidi.Enable function call.
