### ISSUE TITLE
Cancel future note-off events

### ISSUE THREAD

**Issue by psychedelicious** [djipco/webmidi#90]
Notes shared between chords played in succession with specified durations are stopped prematurely. 

For example:

Chord 1 = MIDI notes [0,4,7], duration 1000
Chord 2 = MIDI notes [4, 7, 11], duration 1000

Chord 1 is sent at time = 0. Chord 2 is sent at time = 500. 

MIDI notes 0, 4 and 7 are stopped at time 1000 (as expected, from chord 1's duration).
This means chord 2's MIDI 4 and 7 are also stopped at 1000, when I would like for them to stop at 1500.

            
      t=0         t=500       t=1000        t=1500
      |            |            |             |
    Play 1         |          Stop 1          |
      |            |            |             |
      |-------------------------|             |
                   |--------------------------|
                   |            ^             |
                 Play 2         |           Stop 2 (desired stop of 4 and 7)
                                |             
                      MIDI notes 4 & 7 are stopped here

I cannot find any way in webmidi.js to cancel the pending note-off events - it doesn't look like the event queue is exposed in the Web MIDI API. #52 and the referenced chromium issue are related, but they are to immediately stop _all_ notes.

I am currently managing this like so:

    // store for timeout IDs
    var midiTimeouts = new Array(128).fill(undefined);

    function sendMidiTimeout(noteArr, velocity, duration) {
      for (let i = 0; i < noteArr.length; i++) {
        // clear pending timeouts for the notes about to be played
        clearTimeout(midiTimeouts[noteArr[i]]);
    
        // play without duration
        midiOutput.playNote(noteArr[i], 1, {
          velocity: velocity
        });
    
        // schedule new stopNotes for future
        midiTimeouts[noteArr[i]] = setTimeout(() => {
          midiOutput.stopNote(noteArr[i]);
        }, duration);
      }
    }

Am I missing an existing solution? If not, I would appreciate feedback/criticisms from you experienced folks on how I am handling this situation as well as any suggestions for alternatives.

Thanks!

**Comment by djipco** [comment]
I believe this is the behaviour intended by the MIDI spec. If you send two successive **note on** messages on the same channel, the note will be triggered twice but there won't be two separate instances of the note. The second **note on** will implicitely turn off the first note... because it is the very same note. Then, when you send a **note off**, it will turn off the second note because that's all there is to turn off at this point.

**Note on** and **note off** messages are completely discrete. The device simply looks at inbound messages in the order it receives them. To achieve what you want, you would have to use `playNote()` for each note and use different durations (or you could use separate channels).

Also, as you stated, the event queue is not exposed by the Web MIDI API. So, it is not possible to alter what has already been sent.

Having said that, we will probably add a way to specify different durations for each notes in a chord in v3. This was discussed in issue #75 and your scenario also highlights why this is needed.

**Comment by psychedelicious** [comment]
Thanks.

Using `setTimeout()` is necessary for my application because the user decides when to play chords, and they may play several chords in succession. It's also a very lightweight solution (as far as I can tell). 

I think a queue for note events is something the app should manage and doesn't have any business being in WebMidi.js, as the Web MIDI API does not expose this anyways. 

#75 covers other situations where MIDI is sent programmatically and timings can be known ahead of time, and sounds like something more in the scope of WebMidi.js. 

Closing, thanks!

**Comment by djipco** [comment]
For future reference, please note that version 3 now allows the playback of chords whose individual notes have different durations. This can be achieved by using the new [Note](https://webmidijs.org/docs/v3.0.0-alpha.5/Note.html) object.
